### ISSUE TITLE
Add a map showing all the countries that fellows are located in

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-portfolio-23.APR.PREP.1#10]
Underneath projects and fellows, have an interactive map that displays where everyone is located.

- [ ] When you click on the pin location for that fellow, it gives you a card with information about the fellow (similar to the fellow section

You can chose to have pins or use circular profile pictures to show where everyone is on the map. You could remove the fellows section and replace it with the map.

**Comment by ThGreatExplorer** [comment]
I'd like to try this issue. I don't have any experience with ruby, but this seems fun!

**Comment by k-abirami** [comment]
I'd like to work on this issue as well!

**Comment by ThGreatExplorer** [comment]
Sounds good, what's your discord?

**Comment by k-abirami** [comment]
Hi! My discord is Abirami#4073
