### ISSUE TITLE
Add the pod!

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-portfolio-23.APR.PREP.1#13]
Currently, then repository has members of the MLH team on it, but you should replace them with members of the pod.

You can update information in `_data/fellows.yml`

You should work on:
- [ ] Replacing the images
- [ ] Update the names and locations of each fellow
- [ ] Update the pod number inside of `_config.yml`

**Comment by jaygala223** [comment]
Hi @wrussell1999, I would like to work on this

**Comment by ohsweetmani** [comment]
Hi @wrussell1999 I'd like to work on this as well with @jaygala223

**Comment by jaygala223** [comment]
Hi @akshgpt7, can you confirm if the updated pod number should look like this: Pod 23.APR.1 (for the 3rd task in the issue description). I would like to open a PR that fixes it

**Comment by ttn-ttn** [comment]
Hi @jaygala223  @ohsweetmani, I'm working on issue #4, would it be possible to add every fellow's github username to `_data/fellows.yml`? It would be very helpful to generate the pod stats.

**Comment by jaygala223** [comment]
> Hi @jaygala223 @ohsweetmani, I'm working on issue #4, would it be possible to add every fellow's GitHub username to `_data/fellows.yml`? It would be very helpful to generate the pod stats.

Yes, sure!

**Comment by jaygala223** [comment]
I was adding all the fellows' details in `_data/fellows.yml` and it went like this: 
![image](https://user-images.githubusercontent.com/57001778/230307190-cb56553d-87a3-4755-abba-dc39e877b509.png)

So how do we want to approach this? 

1. Keep only 6 people's images in the top instead of the whole pod *OR*
2. Make some adjustments to fit all the images?

**Comment by jaygala223** [comment]
> I was adding all the fellows' details in `_data/fellows.yml` and it went like this: ![image](https://user-images.githubusercontent.com/57001778/230307190-cb56553d-87a3-4755-abba-dc39e877b509.png)
> 
> So how do we want to approach this?
> 
> 1. Keep only 6 people's images in the top instead of the whole pod _OR_
> 2. Make some adjustments to fit all the images?

Update on this. I and @ohsweetmani discussed adding the image of each fellow in their own card instead of all 15 images being crammed into the profile section. @akshgpt7 what are your thoughts on it?
