### ISSUE TITLE
Improve loading time for images

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-portfolio-23.APR.PREP.1#2]
Currently, images take a while to load as they're quite large. Can we compress the images when they are committed using a GitHub action to improve loading speeds?

**Comment by 0xull** [comment]
Hello Aksh,

I'd love to work/contribute to this issue.

**Comment by jaygala223** [comment]
Hi @IkehAkinyemi, I would like to work on this issue with you.

**Comment by 0xull** [comment]
Happy to have you onboard @jaygala223 🚀
