### ISSUE TITLE
Add pod stats

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-portfolio-23.APR.PREP.1#4]
Add a way to display the number of contributions between fellows. Make a little leaderboard or similar to motivate people to add new issues!

**Comment by ttn-ttn** [comment]
I would like to take on this task. To fetch the user stats automatically, I'm planning to write a Jekyll plugin that periodically calls the Github API and stores the relevant information locally, so it can be displayed without calling the API every time.

**Comment by ThGreatExplorer** [comment]
Can I join this issue?

**Comment by ttn-ttn** [comment]
> Can I join this issue?

No problem on my part :) I would like to focus on the Jekyll plugin side (fetching, selecting, sorting and storing the pertinent user stats), would you like to work on the displaying of the stats? Only if it's okay with you!

**Comment by ThGreatExplorer** [comment]
Assuming that you mean the frontend html, css, javascript, I can do that, but I would also like to contribute to the jekyll plugin since I'm not familiar with ruby and would like to learn.

How do you want to collaborate? Through github repo

**Comment by ttn-ttn** [comment]
Yes, I meant the frontend. I'm just not sure writing the plugin will be enough work for two people haha. Let's do this if you like: I do the frontend and you do the backend, and I'll try to find another backend-related issue to contribute to.
