### ISSUE TITLE
Replace the MLH Fellowship logo with the MLH Prep logo

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-portfolio-23.APR.PREP.1#5]
![Screenshot 2021-09-30 at 18 38 57](https://user-images.githubusercontent.com/34094921/135504106-3f0aacc8-4155-463e-ae81-9433ad10ea13.png)

When you go to the project page, it shows the MLH Fellowship logo at the top. It would be great to replace this with the Prep logo and make sure that's used throughout the website!

**Comment by void-ness** [comment]
Hi, I would like to work on this issue. Kindly assign it to me.

**Comment by archikirar30** [comment]
Heyy , @void-ness  ,I would like to work for this issue , Let's work together , Can @wrussell1999  you assign this task to me?

**Comment by void-ness** [comment]
> Heyy , @void-ness ,I would like to work for this issue , Let's work together , Can @wrussell1999 you assign this task to me?

Sure! Let's work on this together.

**Comment by void-ness** [comment]
One of the approach that can help fix the problem.
1. Identify the file from where this image is being called. 
2. `assets/img` contains lots of images. we need to find the one which has the mlh-prep logo.
3. Replace the `src` value in the `img` tag to refer to the correct image.
4. Do the required css changes (if any).

@archikirar30 what are your views on the same?

**Comment by archikirar30** [comment]
@akshgpt7 can you assign it to me too?

**Comment by archikirar30** [comment]
@void-ness I have searched above image (MLH Prep My project) but it wasn't there, what we can do 
- download this and add inside  `assets/img` folder 
- Call this image in the navbar 
- replace the `previous img` with `final img`
- and can also change some css to add more styling for better view.
what you think?
