### ISSUE TITLE
Add pod blog

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-portfolio-23.APR.PREP.1#7]
It would be awesome to add a blog feature to this repository where fellows can share their insights and people can tune in!

**Comment by ttn-ttn** [comment]
I would like to work on the Jekyll side of this one, with a very bare-bones template. Would anyone be interested in working on improving that template and the UI in general?

**Comment by kristinlam** [comment]
@ttn-ttn I'd like to work with you and improve the template and UI for the blog!
