### ISSUE TITLE
Add a navigation bar

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-portfolio-23.APR.PREP.1#8]
As the portfolio gains more information, it may make sense to add a navigation bar. This bar should include the logo on the left side but only once the page has scrolled down a bit.

**Comment by Ankur6702** [comment]
Can you please assign this issue to me?

**Comment by kristinlam** [comment]
Can I work on this with you @Ankur6702?

**Comment by Ankur6702** [comment]
Definitely @kristinlam , lets work on it together! Can we discuss more about it over discord or on a calendly meeting?
