### ISSUE TITLE
Profile page for each fellow

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-portfolio-23.APR.PREP.1#9]
When you click on each fellows card, it sends you to a separate page which includes more detail such as:

- Description
- Favourite programming languages
- Interests outside of technology
- University

**Comment by akanshaaa19** [comment]
Hii, can you assign this issue to me?

**Comment by suppixie** [comment]
i'd like to work on this issue with you @akanshaaa19
